
function Auxiliary.TBCanIgnition(tp)
	return Duel.GetCurrentChain()==0 and Duel.GetTurnPlayer()==tp and (Duel.GetCurrentPhase()==PHASE_MAIN1 or Duel.GetCurrentPhase()==PHASE_MAIN2)
end


--Proc Ignition Skill
function Auxiliary.TurboDuelStartUp(c,id)
	local e1=Effect.CreateEffect(c) 
	e1:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EVENT_STARTUP)
	e1:SetRange(0x5f)
	e1:SetOperation(Auxiliary.TDStartUp(c,id))
	c:RegisterEffect(e1)	
end
function Auxiliary.TDStartUp(c,id)
	return function(e,tp,eg,ep,ev,re,r,rp)
		Duel.SendtoDeck(c,tp,-2,REASON_RULE)
		local tc=Duel.CreateToken(tp,id)
		e:SetLabelObject(tc)
		Duel.MoveToField(tc,tp,tp,LOCATION_FZONE,POS_FACEUP,true)
		--Speed Counters
		tc:EnableCounterPermit(0x91)
		tc:SetCounterLimit(0x91,12)
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e1:SetCountLimit(1)
		e1:SetRange(LOCATION_FZONE)
		e1:SetCode(EVENT_PHASE_START+PHASE_STANDBY)
		e1:SetOperation(ctop)
		tc:RegisterEffect(e1)
		local ea=Effect.CreateEffect(tc)
		ea:SetType(EFFECT_TYPE_SINGLE)
		ea:SetCode(EFFECT_CANNOT_TO_DECK)
		ea:SetRange(LOCATION_FZONE)
		ea:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE+EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
		tc:RegisterEffect(ea)
		local eb=ea:Clone()
		eb:SetCode(EFFECT_CANNOT_REMOVE)
		tc:RegisterEffect(eb)
		local ec=ea:Clone()
		ec:SetCode(EFFECT_CANNOT_TO_HAND)
		tc:RegisterEffect(ec)
		local ed=ea:Clone()
		ed:SetCode(EFFECT_CANNOT_TO_GRAVE)
		tc:RegisterEffect(ed)
		local ee=ea:Clone()
		ee:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
		ee:SetValue(1)
		tc:RegisterEffect(ee)
		local ef=ea:Clone()
		ef:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
		tc:RegisterEffect(ef)
		local eg=Effect.CreateEffect(tc)
		eg:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
		eg:SetCode(EVENT_LEAVE_FIELD)
		eg:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
		eg:SetOperation(leave)
		tc:RegisterEffect(eg)
		local eh=Effect.CreateEffect(tc)
		eh:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		eh:SetCode(EVENT_CHAIN_END)
		eh:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
		eh:SetLabelObject(tc)
		eh:SetOperation(returnit)
		Duel.RegisterEffect(eh,0)
		
	end
end
function ctop(e,tp,eg,ep,ev,re,r,rp)
	e:GetHandler():AddCounter(0x91,1)
end
function leave(e)
	Duel.SendtoDeck(e:GetHandler(),nil,-2,REASON_RULE)
end
function returnit(e)
	local c=e:GetLabelObject()
	local tp=c:GetControler()
	if Duel.CheckLocation(tp,LOCATION_FZONE,0) then
		Duel.MoveToField(c,tp,tp,LOCATION_FZONE,POS_FACEUP,true)
	end
end